### ISSUE TITLE
Query regarding detection(.bbox.json) generation 

### ISSUE THREAD

**Issue by iabh1shekbasu** [fiveai/detection_calibration#1]
Hi, Thank you for your amazing work. Can you please let me know how can these files be generated?

detections
├── deformable_detr_cityscapes_minival.bbox.json
├── deformable_detr_cityscapes_minitest.bbox.json
├── deformable_detr_coco_minival.bbox.json
├── deformable_detr_coco_minitest.bbox.json
├── ...

**Comment by selimkuzucu** [comment]
Hi @iabh1shekbasu, thank you for your interest in our work. The files you have mentioned are the final detection files in [the COCO format](https://cocodataset.org/#format-results) and can be extracted separately for the individual models. The way to generate them would depend on the framework of your choice.

For our experiments, we utilized the [mmdetection framework](https://github.com/open-mmlab/mmdetection), and specifically its [D-DETR](https://github.com/open-mmlab/mmdetection/tree/main/configs/deformable_detr) implementation for the files you have asked for. To reproduce those files, you need to set the `--format_only` flag to `True` and specify a corresponding `--outfile_prefix`. The way to that would again depend on the version of [mmdetection](https://github.com/open-mmlab/mmdetection) that you have installed, it can either be done through passing the aforementioned flags as command line parameters (for [mmdetection 2.X)](https://mmdetection.readthedocs.io/en/v2.25.0/) or through setting the relevant flags within the `evaluators` (for [mmdetection 3.X)](https://mmdetection.readthedocs.io/en/3.x/). For a more detailed explanation, feel free to see "Dataset and evaluator config" Section under the [mmdetection user guides](https://mmdetection.readthedocs.io/en/latest/user_guides/config.html)

For other established frameworks such as [detectron2](https://github.com/facebookresearch/detectron2), please take a look at their respective repositories as I am not fully familiar with them.  ([Although his may be helpful for detectron2](https://github.com/facebookresearch/detectron2/discussions/3989))

Again, thanks for your interest in our work and do let us know if you need any help with anything else.

**Comment by iabh1shekbasu** [comment]
Hi @selimkuzucu ,

Thank you very much for your reply. I used MMDetection and was able to successfully generate the detection files using the following command:

`python tools/test.py /home/abhishek.basu/desktop/mmdetection/deformable-detr_r50_16xb2-50e_coco.py /home/abhishek.basu/desktop/mmdetection/deformable-detr_r50_16xb2-50e_coco_20221029_210934-6bc7d21b.pth
`

However, I have a few follow-up questions:

1. I am currently using MMDetection version 3.3, and I noticed that while the `test_evaluator` function generates the `.bbox.json` file when provided with the `output_prefix`, the `val_evaluator` does not generate any files. (I am linking the relevant file for your reference). (https://drive.google.com/file/d/1prnIUdFHe_ICULb_2ilEZN0nHT7kcIE1/view?usp=sharing)

2. Regarding the annotation files you provided via Google Drive, am I correct in assuming that they should be placed in `data/coco/annotations`?

3. To generate the detection files, should we replace the `ann_file='/l/users/abhishek.basu/coco/annotations/instances_val2017.json'` with `ann_file='/l/users/abhishek.basu/coco/annotations/calibration_val2017.json'` or `calibration_test2017`? Should this be done only for the `test_dataloader` (line 130) and `test_evaluator` (line 158), or should it also be applied to the `val_dataloader` (line 473) and `val_evaluator` (line 501) ?

4. Finally, to perform calibration:

`calibration_model = DetectionCalibration('data/<dataset_name>/validation.json', 'data/<dataset_name>/test.json')`
Should the paths to `calibration_val2017.json` and `calibration_test2017.json` be provided here?

Thank you in advance for your help!

**Comment by iabh1shekbasu** [comment]
Thank you very much for your kind response. I was successfully able to generate the detection files.
