### ISSUE TITLE
Bug in in utils "linear_regression"

### ISSUE THREAD

**Issue by kmodexc** [fiveai/detection_calibration#2]
Hi there seems to be a wrongly indented return here:

https://github.com/fiveai/detection_calibration/blob/cbefc8f94e01bad41867e4573952f97bbe012e44/src/detection_calibration/utils.py#L288

If one selects classagnostic=True one will get None returned

**Comment by selimkuzucu** [comment]
Hi @kmodexc, thanks for your interest in our work.

And thank you for pointing this out and for your PR! You are indeed correct that there was an indentation issue and I just merged your PR. Please let us know if you have any questions and/or if you encounter any other erroneous segments in our code. Thanks again!
