### ISSUE TITLE
LVIS data missing from drive

### ISSUE THREAD

**Issue by kostas1515** [fiveai/detection_calibration#4]
Dear authors,

Thank you for the nice work. 
I wanted to download the LVIS calibration data but it seems that the google drive folder is empty.
Could you please upload the calibration data?

Kind regards,
Kostas

**Comment by selimkuzucu** [comment]
Hi @kostas1515 ,

Thanks for your interest in our work and thanks for notifying us of this issue. I just added the relevant json files to the same Google Drive link, it should hopefully be all set now.

Please let me know should you have any other questions or concerns!
